project_id = "lzvycoujohuznnqplekx"

[functions.reflection-chat]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.entitlement]
verify_jwt = true

[functions.save-journal]
verify_jwt = true

[functions.generate-journal-titles]
verify_jwt = true

[functions.billing-status]
verify_jwt = true

[functions.billing-cancel]
verify_jwt = true

[functions.billing-reactivate]
verify_jwt = true

[functions.billing-upcoming]
verify_jwt = true